package org.domain.testeam.entity;

// Generated 2017-3-31 20:34:40 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * AlarmInfo generated by hbm2java
 */
@Entity
@Table(name = "alarm_info", catalog = "newbackwards")
public class AlarmInfo implements java.io.Serializable {

	private Integer alarmInfoId;
	private int type;
	private int alarmType;
	private String content;
	private Integer baseId;
	private int enterpriseInfoId;
	private Date insertTime;
	private int insertUser;
	private boolean deleted;

	public AlarmInfo() {
	}

	public AlarmInfo(int type, int alarmType, String content,
			int enterpriseInfoId, Date insertTime, int insertUser,
			boolean deleted) {
		this.type = type;
		this.alarmType = alarmType;
		this.content = content;
		this.enterpriseInfoId = enterpriseInfoId;
		this.insertTime = insertTime;
		this.insertUser = insertUser;
		this.deleted = deleted;
	}

	public AlarmInfo(int type, int alarmType, String content, Integer baseId,
			int enterpriseInfoId, Date insertTime, int insertUser,
			boolean deleted) {
		this.type = type;
		this.alarmType = alarmType;
		this.content = content;
		this.baseId = baseId;
		this.enterpriseInfoId = enterpriseInfoId;
		this.insertTime = insertTime;
		this.insertUser = insertUser;
		this.deleted = deleted;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "alarm_info_id", unique = true, nullable = false)
	public Integer getAlarmInfoId() {
		return this.alarmInfoId;
	}

	public void setAlarmInfoId(Integer alarmInfoId) {
		this.alarmInfoId = alarmInfoId;
	}

	@Column(name = "type", nullable = false)
	public int getType() {
		return this.type;
	}

	public void setType(int type) {
		this.type = type;
	}

	@Column(name = "alarm_type", nullable = false)
	public int getAlarmType() {
		return this.alarmType;
	}

	public void setAlarmType(int alarmType) {
		this.alarmType = alarmType;
	}

	@Column(name = "content", nullable = false, length = 200)
	@NotNull
	@Length(max = 200)
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Column(name = "base_id")
	public Integer getBaseId() {
		return this.baseId;
	}

	public void setBaseId(Integer baseId) {
		this.baseId = baseId;
	}

	@Column(name = "enterprise_info_id", nullable = false)
	public int getEnterpriseInfoId() {
		return this.enterpriseInfoId;
	}

	public void setEnterpriseInfoId(int enterpriseInfoId) {
		this.enterpriseInfoId = enterpriseInfoId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "insert_time", nullable = false, length = 19)
	@NotNull
	public Date getInsertTime() {
		return this.insertTime;
	}

	public void setInsertTime(Date insertTime) {
		this.insertTime = insertTime;
	}

	@Column(name = "insert_user", nullable = false)
	public int getInsertUser() {
		return this.insertUser;
	}

	public void setInsertUser(int insertUser) {
		this.insertUser = insertUser;
	}

	@Column(name = "deleted", nullable = false)
	public boolean isDeleted() {
		return this.deleted;
	}

	public void setDeleted(boolean deleted) {
		this.deleted = deleted;
	}

}
